Draft for advancement opportunities in 2025
OpenFreeEnergy/alchemiscale.org-site pull request #1
Opened 2024-10-08 15:57 UTC by dotsdl

This is our first advancement opportunities perspective.
It functions as a vision for the future, and a starting point for coordinating effort and resources to pursue it.

2024-10-14 17:46 UTC, dotsdl commented
@ianmkenney can I get a review from you on this? It's ready to go!

2024-10-14 22:05 UTC, ianmkenney requested changes
Looks good overall, but there are a few small changes!

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +Originally concieved as a wrapper around [**Folding@Home**](https://foldingathome.org/) for performing alchemical binding free energy calculations routinely and at scale, the project co-evolved with
```suggestion
Originally conceived as a wrapper around [**Folding@Home**](https://foldingathome.org/) for performing alchemical binding free energy calculations routinely and at scale, the project co-evolved with the [**Open Free Energy (OpenFE)**](https://openfree.energy/) data model to become a general-purpose, high-throughput execution system that can take advantage of a variety of distributed compute.
```

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +Exploring thes space of possibilities for different `Strategy`s would add richness to the portfolio of adaptive sampling approaches available.
this space

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +We are currently working on iniitial support for `Strategy`s (see [**where we are**]({{< ref "#where-we-are" >}})), but beyond this there may be a good case for being able to *stack* multiple `Strate
initial

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +It also gives a very clear signal to the execution system what should be preserved post-`ProtocolDAG` execution, requring no heuristics or guessing.
requiring

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +In addition to the other areas above, there are more "boring" areas that could greatly improve **alchemiscale**'s operations model.
In addition to the other areas mentioned above, there are several key areas that could significantly enhance alchemiscale's operations model.

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +then build a framework for updating data models on deployed systems in compliance with those guarantees.
inconsistent line break, if you care

2024-10-14 22:05 UTC, ianmkenney commented on content/opportunities/alchemiscale-2025/index.md
> +Administrators are even worse-off currently, as managing users on an **alchemiscale** instance requires execution of CLI commands against the server, which is often awkward and tedious. Tracking comp
link to cypher

2024-10-15 12:57 UTC, dotsdl commented
Thanks @ianmkenney! I've implemented all your requested changes!

2024-10-15 14:32 UTC, merged